services:
  symfony:
    image: shinsenter/symfony:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "pgsql://app:app@postgres:5432/app?serverVersion=16&options=-csearch_path=mdp_products,public"
      MAILER_DSN: "smtp://localhost:25"

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./mis_scripts_postgres:/scripts
      - ./mis_csvs:/csvs_postgres

  pgadmin:
    image: dpage/pgadmin4:9.8
    restart: always
    depends_on:
      - postgres
    ports:
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  node:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3035:3000"
    command: sh -c "npm install && npm run dev"

volumes:
  database_data:
  pgadmin_data: