
services:
  symfony:
    image: shinsenter/symfony
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/app?serverVersion=8.0&charset=utf8mb4"

  mysql:
    image: mysql:8.0
    command: --local-infile=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mis_csvs:/csvs
      - ./mis_scripts_mysql:/scripts

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8087:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: 3306

volumes:
  mysql_data: